"""Create Tables

Revision ID: d3b61d4dc259
Revises:
Create Date: 2022-06-25 00:33:40.067750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d3b61d4dc259"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("youtube_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("youtube_id"),
    )
    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("youtube_id", sa.String(), nullable=False),
        sa.Column("author_display_name", sa.String(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("parent_id", sa.String(), nullable=True),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("video_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video.youtube_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("youtube_id"),
    )
    op.create_table(
        "comment_thread",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("youtube_id", sa.String(), nullable=False),
        sa.Column("video_id", sa.String(), nullable=False),
        sa.Column("top_level_comment_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["top_level_comment_id"],
            ["comment.youtube_id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video.youtube_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("youtube_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comment_thread")
    op.drop_table("comment")
    op.drop_table("video")
    # ### end Alembic commands ###
